version: '3'

services:
  cards-php:
    build:
      context: docker/images/php/
      dockerfile: Dockerfile
    depends_on:
      - "cards-db"
    volumes:
      - .:/var/www/project
  cards-nginx:
    image: nginx:alpine
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - ./docker/hosts:/etc/nginx/conf.d
      - .:/var/www/project
      - ./docker/logs:/var/log/nginx
    depends_on:
      - "cards-php"
  cards-db:
    image: postgis/postgis:13-3.1-alpine
    ports:
      - "127.0.0.1:54328:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/database/db-data:/data/postgres
